// AUTO-GENERATED by extract_simple.d - Do not edit
// Regenerate with: rdmd extract_simple.d stencils/stencils.o
// Source: ~/projects/copy-patch-arm64/
module codegen.native.stencil_table;

enum HoleKind : ubyte {
    imm16_lo,    // Low 16 bits of 32-bit immediate
    imm16_hi,    // High 16 bits (in MOVK)
    imm16_lo_2,  // Second hole, low bits
    imm16_hi_2,  // Second hole, high bits
}

struct Hole {
    uint offset;
    HoleKind kind;
}

struct Stencil {
    string name;
    immutable(ubyte)[] code;
    immutable(Hole)[] holes;
}

immutable stencil_add_i32 = Stencil(
    "add_i32",
    cast(immutable ubyte[])[
        0x20,0x00,0x00,0x8b
    ],
    []
);

immutable stencil_sub_i32 = Stencil(
    "sub_i32",
    cast(immutable ubyte[])[
        0x00,0x00,0x01,0xcb
    ],
    []
);

immutable stencil_mul_i32 = Stencil(
    "mul_i32",
    cast(immutable ubyte[])[
        0x20,0x7c,0x00,0x9b
    ],
    []
);

immutable stencil_div_i32 = Stencil(
    "div_i32",
    cast(immutable ubyte[])[
        0x00,0x0c,0xc1,0x9a
    ],
    []
);

immutable stencil_mod_i32 = Stencil(
    "mod_i32",
    cast(immutable ubyte[])[
        0x08,0x0c,0xc1,0x9a,0x00,0x81,0x01,0x9b
    ],
    []
);

immutable stencil_and_i32 = Stencil(
    "and_i32",
    cast(immutable ubyte[])[
        0x20,0x00,0x00,0x8a
    ],
    []
);

immutable stencil_or_i32 = Stencil(
    "or_i32",
    cast(immutable ubyte[])[
        0x20,0x00,0x00,0xaa
    ],
    []
);

immutable stencil_xor_i32 = Stencil(
    "xor_i32",
    cast(immutable ubyte[])[
        0x20,0x00,0x00,0xca
    ],
    []
);

immutable stencil_shl_i32 = Stencil(
    "shl_i32",
    cast(immutable ubyte[])[
        0x28,0x7c,0x40,0x93,0x00,0x20,0xc8,0x9a
    ],
    []
);

immutable stencil_shr_i32 = Stencil(
    "shr_i32",
    cast(immutable ubyte[])[
        0x28,0x7c,0x40,0x93,0x00,0x28,0xc8,0x9a
    ],
    []
);

immutable stencil_eq_i32 = Stencil(
    "eq_i32",
    cast(immutable ubyte[])[
        0x1f,0x00,0x01,0xeb,0xe0,0x17,0x9f,0x1a
    ],
    []
);

immutable stencil_ne_i32 = Stencil(
    "ne_i32",
    cast(immutable ubyte[])[
        0x1f,0x00,0x01,0xeb,0xe0,0x07,0x9f,0x1a
    ],
    []
);

immutable stencil_lt_i32 = Stencil(
    "lt_i32",
    cast(immutable ubyte[])[
        0x1f,0x00,0x01,0xeb,0xe0,0xa7,0x9f,0x1a
    ],
    []
);

immutable stencil_le_i32 = Stencil(
    "le_i32",
    cast(immutable ubyte[])[
        0x1f,0x00,0x01,0xeb,0xe0,0xc7,0x9f,0x1a
    ],
    []
);

immutable stencil_gt_i32 = Stencil(
    "gt_i32",
    cast(immutable ubyte[])[
        0x1f,0x00,0x01,0xeb,0xe0,0xd7,0x9f,0x1a
    ],
    []
);

immutable stencil_ge_i32 = Stencil(
    "ge_i32",
    cast(immutable ubyte[])[
        0x1f,0x00,0x01,0xeb,0xe0,0xb7,0x9f,0x1a
    ],
    []
);

immutable stencil_load_imm32 = Stencil(
    "load_imm32",
    cast(immutable ubyte[])[
        0x20,0x00,0x80,0x52,0xa0,0xd5,0xbb,0x72
    ],
    [Hole(0, HoleKind.imm16_lo), Hole(4, HoleKind.imm16_hi)]
);

immutable stencil_load_imm16 = Stencil(
    "load_imm16",
    cast(immutable ubyte[])[
        0x20,0x00,0x80,0x52
    ],
    [Hole(0, HoleKind.imm16_lo)]
);

immutable stencil_load_i32 = Stencil(
    "load_i32",
    cast(immutable ubyte[])[
        0x28,0x00,0x80,0x52,0xa8,0xd5,0xbb,0x72,0x00,0x68,0xa8,0xb8
    ],
    [Hole(0, HoleKind.imm16_lo), Hole(4, HoleKind.imm16_hi)]
);

immutable stencil_store_i32 = Stencil(
    "store_i32",
    cast(immutable ubyte[])[
        0x28,0x00,0x80,0x52,0xa8,0xd5,0xbb,0x72,0x01,0x68,0x28,0xb8
    ],
    [Hole(0, HoleKind.imm16_lo), Hole(4, HoleKind.imm16_hi)]
);

immutable stencil_load_i64 = Stencil(
    "load_i64",
    cast(immutable ubyte[])[
        0x28,0x00,0x80,0x52,0xa8,0xd5,0xbb,0x72,0x00,0x68,0x68,0xf8
    ],
    [Hole(0, HoleKind.imm16_lo), Hole(4, HoleKind.imm16_hi)]
);

immutable stencil_store_i64 = Stencil(
    "store_i64",
    cast(immutable ubyte[])[
        0x28,0x00,0x80,0x52,0xa8,0xd5,0xbb,0x72,0x01,0x68,0x28,0xf8
    ],
    [Hole(0, HoleKind.imm16_lo), Hole(4, HoleKind.imm16_hi)]
);

immutable stencil_return_void = Stencil(
    "return_void",
    cast(immutable ubyte[])[
        0xc0,0x03,0x5f,0xd6
    ],
    []
);

immutable stencil_return_val = Stencil(
    "return_val",
    cast(immutable ubyte[])[
        0xc0,0x03,0x5f,0xd6
    ],
    []
);

immutable Stencil*[string] stencilTable;

shared static this() {
    stencilTable["add_i32"] = &stencil_add_i32;
    stencilTable["sub_i32"] = &stencil_sub_i32;
    stencilTable["mul_i32"] = &stencil_mul_i32;
    stencilTable["div_i32"] = &stencil_div_i32;
    stencilTable["mod_i32"] = &stencil_mod_i32;
    stencilTable["and_i32"] = &stencil_and_i32;
    stencilTable["or_i32"] = &stencil_or_i32;
    stencilTable["xor_i32"] = &stencil_xor_i32;
    stencilTable["shl_i32"] = &stencil_shl_i32;
    stencilTable["shr_i32"] = &stencil_shr_i32;
    stencilTable["eq_i32"] = &stencil_eq_i32;
    stencilTable["ne_i32"] = &stencil_ne_i32;
    stencilTable["lt_i32"] = &stencil_lt_i32;
    stencilTable["le_i32"] = &stencil_le_i32;
    stencilTable["gt_i32"] = &stencil_gt_i32;
    stencilTable["ge_i32"] = &stencil_ge_i32;
    stencilTable["load_imm32"] = &stencil_load_imm32;
    stencilTable["load_imm16"] = &stencil_load_imm16;
    stencilTable["load_i32"] = &stencil_load_i32;
    stencilTable["store_i32"] = &stencil_store_i32;
    stencilTable["load_i64"] = &stencil_load_i64;
    stencilTable["store_i64"] = &stencil_store_i64;
    stencilTable["return_void"] = &stencil_return_void;
    stencilTable["return_val"] = &stencil_return_val;
}

const(Stencil)* getStencil(string name) {
    if (auto p = name in stencilTable) return *p;
    return null;
}
